language: go

go:
  - 1.6

script:
  - cd ../../
  - mv 932280190 pingcap
  - cd pingcap/pd
  - make dev

matrix:
  include:
  - go: 1.7
    install:
      - go get github.com/mattn/goveralls
    env:
      - TRAVIS_COVERAGE=1
    script:
      - cd ../../
      - mv 932280190 pingcap
      - cd pingcap/pd
      - make dev
    after_success:
      - travis_wait make travis_coverage
